### ISSUE TITLE
Incorrect couchdb_database_data_size metric value in CouchDB v.2.3.1

### ISSUE THREAD

**Issue by atrishin84** [gesellix/couchdb-prometheus-exporter#76]
Couchdb-prometheus-exporter do not collect couchdb_database_data_size metric with CouchDB v.2.3.1. Values of this metric constantly zero.

In accordance with official documentation:
https://docs.couchdb.org/en/stable/whatsnew/3.0.html?highlight=data_size#deprecated-feature-removal
disk_size and data_size was deprecated.

CouchDB v.2.3.1 shows database size as:
"sizes":{
	"file": 183235000,
	"external": 190740298,
	"active": 170415393
}

**Comment by gesellix** [comment]
Hey, thanks for the bug report! I have a fix prepared at #74 for CouchDB 3.x.
Would you like to check whether this also fixes your issue for CouchDB 2.x? If so, please run the preview like this (assuming you have Docker installed on a machine with access to your CouchDB instance):

```
# http://host.docker.internal:5984 needs to be replaced with your CouchDB's address, username+password, too :)
docker run --rm -it -p 9984:9984 gesellix/couchdb-prometheus-exporter:partitioned-dbs --couchdb.username=admin --couchdb.password=admin --databases=_all_dbs --couchdb.uri=http://host.docker.internal:5984
```

**Comment by atrishin84** [comment]
I have performed next task:
 - update CouchDB from v.2.3.1 to v.3.1.0;
 - update couchdb-prometheus-exporter from v27.2.0 to v28.0.0.
Bug is actual.

**Comment by gesellix** [comment]
The fix mentioned in my last comment hasn't released, yet, that's why I suggested you to use the pre-released Docker image. I've prepared a fix in #77, though, but I still have to manually reproduce your issue. Thank you for your patience.

**Comment by atrishin84** [comment]
I had test with use the pre-released Docker image. Bug was fixed. couchdb_database_data_size and couchdb_database_disk_size metrics has a correct value.

**Comment by gesellix** [comment]
Thanks for testing!

My local tests show that CouchDB 2.3.1 responds with the data_* values at both places (at top level and unter `sizes`). So I'm a bit surprised that your setup doesn't work. Can you please verify if other metrics like couchdb_up are correct?

Nevertheless I'm going to release #77 today.

**Comment by gesellix** [comment]
-> https://github.com/gesellix/couchdb-prometheus-exporter/releases/tag/v28.0.1

The Docker image should also be available soon.

I'm going to close this issue now, because I believe your problem should be fixed, but please re-open in case the error still exists.
Thanks for your patience!
